import { Reem_Kufi, Poppins } from "next/font/google";
import "./globals.css";

const reemakufi = Reem_Kufi({
  variable: "--font-reemakufi",
  subsets: ["latin"],
  weight: ['500','700']
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['400','700']
  
});

export const metadata = {
  title: "Chamal's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${reemakufi.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
